version: '3.2'
services:
  iris:
    build: .
    restart: always
    command: --check-caps false
    container_name: restforms2
    ports:
      - 1972
      - 52773:52773
    volumes:
      - .:/app
